name: Build ndpiReader for OpenWrt

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build ndpiReader

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Download OpenWrt SDK
        run: |
          wget https://downloads.openwrt.org/releases/23.05.3/targets/mediatek/filogic/openwrt-sdk-23.05.3-mediatek-filogic_gcc-12.3.0_musl.Linux-x86_64.tar.xz
          tar -xf openwrt-sdk-*.tar.xz
          SDK_DIR=$(find . -maxdepth 1 -type d -name "openwrt-sdk*" | head -n 1)
          echo "SDK_DIR=$SDK_DIR" >> $GITHUB_ENV

      - name: Link ndpi package
        run: |
          ln -s $(pwd)/ndpi ${{ env.SDK_DIR }}/package/ndpi

      - name: Enable ndpiReader in config
        run: |
          cd ${{ env.SDK_DIR }}
          echo "CONFIG_PACKAGE_ndpiReader=y" >> .config
          make defconfig

      - name: Build package
        run: |
          cd ${{ env.SDK_DIR }}
          make package/ndpiReader/compile V=s -j$(nproc)

      - name: Upload .ipk
        uses: actions/upload-artifact@v4
        with:
          name: ndpiReader-ipk
          path: ${{ env.SDK_DIR }}/bin/packages
